/* =====================================================
   data.js — Contenu pédagogique
   Cahier de vacances 3e → 2nde
   Sources : programmes EN, annales brevet APMEP 2024-2025
   ===================================================== */

/* ===== CITATIONS MOTIVANTES ===== */
const QUOTES = [
  { text: "Les mathématiques, c'est l'art de donner le même nom à des choses différentes.", author: "Henri Poincaré" },
  { text: "L'imagination est plus importante que le savoir.", author: "Albert Einstein" },
  { text: "Il n'existe pas de problème insoluble, il n'existe que des problèmes qu'on n'a pas encore résolus.", author: "Anonyme" },
  { text: "Le succès, c'est d'aller d'échec en échec sans perdre son enthousiasme.", author: "Winston Churchill" },
  { text: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas ; c'est parce que nous n'osons pas qu'elles sont difficiles.", author: "Sénèque" },
  { text: "Les mathématiques sont la musique de la raison.", author: "James Joseph Sylvester" },
  { text: "Chaque expert a été un jour un débutant.", author: "Hellen Hayes" },
  { text: "La persévérance est la reine des vertus.", author: "Proverbe" },
  { text: "Tu n'as pas encore échoué. Tu as juste trouvé des façons qui ne marchent pas.", author: "Thomas Edison" },
  { text: "Le génie, c'est 1 % d'inspiration et 99 % de transpiration.", author: "Thomas Edison" },
  { text: "La rigueur en mathématiques ne s'oppose pas à la créativité, elle la libère.", author: "André Weil" },
  { text: "Prendre confiance en soi, c'est découvrir que l'on était capable depuis le début.", author: "Anonyme" },
];

/* ===== BADGES ===== */
const BADGES = [
  { id: "premier-pas", nom: "Premier pas !", icon: "🚀", desc: "Premier exercice complété", condition: "first_exercise" },
  { id: "curieux", nom: "Curieux·se", icon: "🔍", desc: "As consulté une aide", condition: "first_hint" },
  { id: "jour-1", nom: "Jour 1 !", icon: "🌟", desc: "Première journée de travail", condition: "first_day" },
  { id: "regulier-3", nom: "Régulier·e", icon: "📅", desc: "3 jours consécutifs", condition: "streak_3" },
  { id: "en-feu", nom: "En feu ! 🔥", icon: "🔥", desc: "7 jours consécutifs", condition: "streak_7" },
  { id: "champion", nom: "Champion(ne)", icon: "🏆", desc: "14 jours consécutifs", condition: "streak_14" },
  { id: "as-fractions", nom: "As des fractions", icon: "½", desc: "Tous les exos fractions réussis", condition: "theme_fractions" },
  { id: "geometre", nom: "Géomètre", icon: "📐", desc: "Tous les exos géométrie réussis", condition: "theme_geometrie" },
  { id: "algebriste", nom: "Algébriste", icon: "🧮", desc: "Tous les exos algèbre réussis", condition: "theme_algebre" },
  { id: "statisticien", nom: "Statisticien·ne", icon: "📊", desc: "Tous les exos stats réussis", condition: "theme_stats" },
  { id: "probabiliste", nom: "Probabiliste", icon: "🎲", desc: "Tous les exos probas réussis", condition: "theme_proba" },
  { id: "parcours-a", nom: "Remise en forme !", icon: "💪", desc: "Parcours A terminé", condition: "parcours_A" },
  { id: "parcours-b", nom: "Étoile montante", icon: "⭐", desc: "Parcours B terminé", condition: "parcours_B" },
  { id: "parcours-c", nom: "Cap Seconde !", icon: "🎯", desc: "Parcours C terminé", condition: "parcours_C" },
  { id: "auto-10", nom: "Machine à calculer", icon: "⚡", desc: "10 automatismes réussis", condition: "auto_10" },
  { id: "auto-20", nom: "Flash !", icon: "🌩️", desc: "20 automatismes réussis", condition: "auto_20" },
  { id: "perseverant", nom: "Persévérant·e", icon: "🎖️", desc: "30 exercices complétés", condition: "total_30" },
  { id: "expert", nom: "Expert(e)", icon: "🎓", desc: "Tous les parcours terminés + 20 automatismes", condition: "all_done" },
  { id: "brevet-style", nom: "Style brevet", icon: "📝", desc: "5 exercices de type brevet réussis", condition: "brevet_5" },
];

/* ===== MESSAGES D'ENCOURAGEMENT ===== */
const BRAVO_MESSAGES = [
  "Excellent travail ! Continue comme ça ! 🌟",
  "Bravo ! Tu progresses vraiment bien ! 💪",
  "Super ! Chaque exercice te rapproche de la seconde ! 🚀",
  "Parfait ! Tu maîtrises ce point. Passe au suivant ! ✨",
  "Génial ! C'est exactement la bonne démarche ! 🎉",
  "Très bien ! La régularité paie toujours. 🏆",
  "Impressionnant ! Tu n'as pas abandonné, et ça se voit ! 💫",
];

const COURAGE_MESSAGES = [
  "C'est difficile, mais tu en es capable ! Regarde le conseil 💡",
  "Pas de panique ! Les erreurs font partie de l'apprentissage 🌱",
  "Persiste ! Chaque difficulté surmontée te rend plus fort·e 💪",
  "N'abandonne pas ! La solution est à portée de main ✊",
];

/* ===== EXERCICES — PARCOURS A (Remise en forme) ===== */
/* Niveau : CM2 à 5ème — Bases solides */

const EXERCICES_A = [
  {
    id: "A-001",
    titre: "Addition de fractions",
    theme: "fractions",
    type: "Calcul",
    niveau: 1,
    xp: 10,
    papier: true,
    brevet: false,
    enonce: `Calcule les sommes suivantes en donnant le résultat sous forme irréductible :\n\n$$\\frac{3}{4} + \\frac{5}{6} \\qquad \\qquad \\frac{7}{12} - \\frac{1}{4}$$`,
    aide: `Pour additionner des fractions, il faut un **dénominateur commun**.\n\nPour $\\frac{3}{4} + \\frac{5}{6}$, le PPCM de 4 et 6 est **12**.\n$$\\frac{3}{4} = \\frac{9}{12} \\qquad \\frac{5}{6} = \\frac{10}{12}$$`,
    solution: `$$\\frac{3}{4} + \\frac{5}{6} = \\frac{9}{12} + \\frac{10}{12} = \\frac{19}{12}$$\n\n$$\\frac{7}{12} - \\frac{1}{4} = \\frac{7}{12} - \\frac{3}{12} = \\frac{4}{12} = \\frac{1}{3}$$\n\n$\\frac{19}{12}$ est irréductible car PGCD(19, 12) = 1.`,
  },
  {
    id: "A-002",
    titre: "Multiplication et division de fractions",
    theme: "fractions",
    type: "Calcul",
    niveau: 1,
    xp: 10,
    papier: true,
    brevet: false,
    enonce: `Calcule en simplifiant au maximum :\n$$\\frac{2}{3} \\times \\frac{9}{4} \\qquad \\qquad \\frac{5}{6} \\div \\frac{10}{3}$$`,
    aide: `Pour **multiplier** : on multiplie numérateur × numérateur et dénominateur × dénominateur.\n\nPour **diviser** : on multiplie par l'inverse : $\\frac{a}{b} \\div \\frac{c}{d} = \\frac{a}{b} \\times \\frac{d}{c}$`,
    solution: `$$\\frac{2}{3} \\times \\frac{9}{4} = \\frac{18}{12} = \\frac{3}{2}$$\n\n$$\\frac{5}{6} \\div \\frac{10}{3} = \\frac{5}{6} \\times \\frac{3}{10} = \\frac{15}{60} = \\frac{1}{4}$$`,
  },
  {
    id: "A-003",
    titre: "Problème de proportionnalité",
    theme: "fractions",
    type: "Problème",
    niveau: 1,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `Une recette de gâteau pour **4 personnes** nécessite 320 g de farine, 150 g de beurre et $\\frac{3}{4}$ de litre de lait.\n\n**Question :** Quelles quantités faut-il pour faire ce gâteau pour **7 personnes** ?`,
    aide: `C'est un problème de **proportionnalité**.\n\nD'abord calcule la quantité pour 1 personne, puis multiplie par 7.\n\nEx. farine : $320 \\div 4 = 80$ g par personne`,
    solution: `Pour 1 personne :\n- Farine : $320 \\div 4 = 80$ g\n- Beurre : $150 \\div 4 = 37{,}5$ g\n- Lait : $\\frac{3}{4} \\div 4 = \\frac{3}{16}$ L\n\nPour 7 personnes :\n- Farine : $80 \\times 7 = \\mathbf{560}$ **g**\n- Beurre : $37{,}5 \\times 7 = \\mathbf{262{,}5}$ **g**\n- Lait : $\\frac{3}{16} \\times 7 = \\frac{21}{16} \\approx \\mathbf{1{,}31}$ **L**`,
  },
  {
    id: "A-004",
    titre: "Pourcentages — Soldes",
    theme: "proportionnalite",
    type: "Problème",
    niveau: 1,
    xp: 15,
    papier: false,
    brevet: true,
    enonce: `Lors des soldes, une boutique applique des réductions.\n\n- Un manteau à **120 €** est soldé à **−25 %**\n- Une paire de chaussures à **85 €** est soldée à **−30 %**\n\n**a)** Calcule le prix de chaque article après réduction.\n**b)** Si tu achètes les deux, combien économises-tu par rapport au prix initial ?`,
    aide: `Réduction de **p %** ⟹ on multiplie par $(1 - \\frac{p}{100})$.\n\nEx : −25 % ⟹ on multiplie par $0{,}75$`,
    solution: `**a)**\n- Manteau : $120 \\times 0{,}75 = \\mathbf{90}$ **€**\n- Chaussures : $85 \\times 0{,}70 = \\mathbf{59{,}50}$ **€**\n\n**b)**\nPrix total avant : $120 + 85 = 205$ €\nPrix total après : $90 + 59{,}50 = 149{,}50$ €\nÉconomie : $205 - 149{,}50 = \\mathbf{55{,}50}$ **€**`,
  },
  {
    id: "A-005",
    titre: "Théorème de Pythagore",
    theme: "geometrie",
    type: "Géométrie",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `Dans le triangle $ABC$, l'angle en $B$ est droit, $AB = 6$ cm et $BC = 8$ cm.\n\n**a)** Fais un schéma du triangle.\n**b)** Calcule la longueur $AC$.\n**c)** Vérifie que le triangle $PQR$ avec $PQ = 5$, $QR = 12$ et $PR = 13$ est rectangle. En quel sommet ?`,
    aide: `Dans un triangle rectangle, l'hypoténuse est le côté le plus long, **opposé à l'angle droit**.\n\n**Théorème :** $AC^2 = AB^2 + BC^2$\n\n**Réciproque :** Si $a^2 = b^2 + c^2$, alors le triangle est rectangle en l'angle opposé à $a$.`,
    solution: `**b)** $AC^2 = 6^2 + 8^2 = 36 + 64 = 100$\nDonc $AC = \\sqrt{100} = \\mathbf{10}$ **cm**\n\n**c)** $PR^2 = 13^2 = 169$ et $PQ^2 + QR^2 = 25 + 144 = 169$\nComme $PR^2 = PQ^2 + QR^2$, le triangle est **rectangle en Q** (l'angle droit est en Q, opposé à PR).`,
  },
  {
    id: "A-006",
    titre: "Aires et périmètres",
    theme: "geometrie",
    type: "Calcul",
    niveau: 1,
    xp: 10,
    papier: true,
    brevet: false,
    enonce: `Calcule l'aire et le périmètre de chaque figure :\n\n**a)** Un rectangle de longueur 12 cm et largeur 5 cm.\n**b)** Un triangle de base 8 cm et hauteur 6 cm, avec les deux autres côtés mesurant 7 cm chacun.\n**c)** Un disque de rayon 4 cm (résultat en cm² arrondi au dixième). On prendra $\\pi \\approx 3{,}14$.`,
    aide: `- Aire rectangle = $L \\times l$\n- Aire triangle = $\\frac{\\text{base} \\times \\text{hauteur}}{2}$\n- Aire disque = $\\pi r^2$\n- Périmètre = somme des côtés (ou $2\\pi r$ pour le cercle)`,
    solution: `**a)** Aire = $12 \\times 5 = \\mathbf{60}$ **cm²** ; Périmètre = $2(12 + 5) = \\mathbf{34}$ **cm**\n\n**b)** Aire = $\\frac{8 \\times 6}{2} = \\mathbf{24}$ **cm²** ; Périmètre = $8 + 7 + 7 = \\mathbf{22}$ **cm**\n\n**c)** Aire = $3{,}14 \\times 4^2 = 3{,}14 \\times 16 \\approx \\mathbf{50{,}2}$ **cm²** ; Circonférence = $2 \\times 3{,}14 \\times 4 \\approx \\mathbf{25{,}1}$ **cm**`,
  },
  {
    id: "A-007",
    titre: "Équation du 1er degré",
    theme: "algebre",
    type: "Calcul",
    niveau: 1,
    xp: 10,
    papier: true,
    brevet: false,
    enonce: `Résous les équations suivantes (pense à vérifier ta solution) :\n\n**a)** $3x - 7 = 2x + 5$\n**b)** $\\frac{x+1}{2} = \\frac{x-3}{4} + 2$\n**c)** $2(3x - 1) = 4(x + 2) - 6$`,
    aide: `L'objectif est d'**isoler** $x$ d'un côté.\n\nPour éliminer les fractions, multiplie tous les membres par le dénominateur commun.\n\nVérifie toujours en réinjectant ta solution dans l'équation de départ !`,
    solution: `**a)** $3x - 2x = 5 + 7 \\Rightarrow x = \\mathbf{12}$\n\nVérif : $3(12) - 7 = 29 = 2(12) + 5$ ✓\n\n**b)** On multiplie par 4 : $2(x+1) = (x-3) + 8$\n$2x + 2 = x + 5 \\Rightarrow x = \\mathbf{3}$\n\n**c)** $6x - 2 = 4x + 8 - 6 = 4x + 2$\n$2x = 4 \\Rightarrow x = \\mathbf{2}$`,
  },
  {
    id: "A-008",
    titre: "Problème avec équation (style brevet)",
    theme: "algebre",
    type: "Problème",
    niveau: 2,
    xp: 20,
    papier: true,
    brevet: true,
    enonce: `**Problème :** Léa et Tom jouent aux cartes. Léa a **3 fois plus de cartes** que Tom. Ensemble, ils en ont **84**.\n\n**a)** Pose une équation pour trouver le nombre de cartes de Tom.\n**b)** Résous l'équation.\n**c)** Combien de cartes a chacun ?`,
    aide: `Appelle $x$ le nombre de cartes de Tom.\n\nAlors Léa en a $3x$.\n\nEnsemble : $x + 3x = 84$`,
    solution: `**a)** Soit $x$ le nombre de cartes de Tom. Léa en a $3x$.\n$$x + 3x = 84$$\n\n**b)** $4x = 84 \\Rightarrow x = \\mathbf{21}$\n\n**c)** Tom : **21 cartes**, Léa : $3 \\times 21 = $ **63 cartes**.\n\nVérif : $21 + 63 = 84$ ✓`,
  },
  {
    id: "A-009",
    titre: "Puissances et calculs",
    theme: "calcul",
    type: "Calcul",
    niveau: 1,
    xp: 10,
    papier: false,
    brevet: false,
    enonce: `Calcule sans calculatrice :\n\n**a)** $2^5 \\times 2^{-3}$\n**b)** $\\left(\\frac{3}{2}\\right)^3$\n**c)** $10^4 \\times 10^{-2} \\div 10^3$\n**d)** $(-2)^4 - (-3)^2$`,
    aide: `Règles des puissances :\n- $a^m \\times a^n = a^{m+n}$\n- $a^m \\div a^n = a^{m-n}$\n- $(a^m)^n = a^{mn}$\n\n**Attention !** $(-2)^4 = +16$ car l'exposant 4 est pair.`,
    solution: `**a)** $2^5 \\times 2^{-3} = 2^{5-3} = 2^2 = \\mathbf{4}$\n\n**b)** $\\left(\\frac{3}{2}\\right)^3 = \\frac{3^3}{2^3} = \\frac{27}{8} = \\mathbf{3{,}375}$\n\n**c)** $10^{4-2-3} = 10^{-1} = \\mathbf{0{,}1}$\n\n**d)** $(-2)^4 - (-3)^2 = 16 - 9 = \\mathbf{7}$`,
  },
  {
    id: "A-010",
    titre: "Volume d'un pavé droit et d'un cylindre",
    theme: "geometrie",
    type: "Calcul",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `**a)** Une boîte de jus de fruit a la forme d'un pavé droit de dimensions 6 cm × 4 cm × 12 cm. Quel est son volume en cm³ ? En litres ?\n\n**b)** Une canette cylindrique a un rayon de 3{,}3 cm et une hauteur de 11 cm. Calcule son volume en cm³ (arrondi au cm³). On prend $\\pi \\approx 3{,}14$.`,
    aide: `- Volume pavé droit : $V = L \\times l \\times h$\n- Volume cylindre : $V = \\pi r^2 h$\n- $1$ L $= 1000$ cm³`,
    solution: `**a)** $V = 6 \\times 4 \\times 12 = \\mathbf{288}$ **cm³** $= 0{,}288$ L\n\n**b)** $V = 3{,}14 \\times 3{,}3^2 \\times 11 = 3{,}14 \\times 10{,}89 \\times 11 \\approx \\mathbf{376}$ **cm³**`,
  },
];

/* ===== EXERCICES — PARCOURS B (Les essentiels — niveau 3ème) ===== */

const EXERCICES_B = [
  {
    id: "B-001",
    titre: "Identités remarquables — Développement",
    theme: "algebre",
    type: "Calcul",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `Développe et réduis :\n\n**a)** $(2x + 3)^2$\n**b)** $(5 - x)^2$\n**c)** $(3x + 4)(3x - 4)$\n**d)** $(x + 1)(x - 1) + (x + 1)^2$`,
    aide: `Les **trois identités remarquables** à connaître par cœur :\n$$\\mathbf{(a+b)^2 = a^2 + 2ab + b^2}$$\n$$\\mathbf{(a-b)^2 = a^2 - 2ab + b^2}$$\n$$\\mathbf{(a+b)(a-b) = a^2 - b^2}$$`,
    solution: `**a)** $(2x+3)^2 = 4x^2 + 12x + 9$\n\n**b)** $(5-x)^2 = 25 - 10x + x^2$\n\n**c)** $(3x+4)(3x-4) = 9x^2 - 16$\n\n**d)** $(x^2-1) + (x^2+2x+1) = 2x^2 + 2x$`,
  },
  {
    id: "B-002",
    titre: "Factorisation",
    theme: "algebre",
    type: "Calcul",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `Factorise les expressions suivantes :\n\n**a)** $4x^2 - 9$\n**b)** $x^2 + 6x + 9$\n**c)** $3x^2 - 12x$\n**d)** $x^2 - 5x + 6$ (utilise le fait que $x^2 - 5x + 6 = (x - 2)(x - 3)$ — vérifie-le !)`,
    aide: `Commence par chercher un **facteur commun**.\n\nEnsuite regarde si tu peux utiliser une identité remarquable :\n- $a^2 - b^2 = (a-b)(a+b)$\n- $a^2 + 2ab + b^2 = (a+b)^2$`,
    solution: `**a)** $4x^2 - 9 = (2x)^2 - 3^2 = (2x-3)(2x+3)$\n\n**b)** $x^2 + 6x + 9 = (x+3)^2$\n\n**c)** $3x^2 - 12x = 3x(x - 4)$\n\n**d)** Vérif : $(x-2)(x-3) = x^2 - 3x - 2x + 6 = x^2 - 5x + 6$ ✓\nDonc $x^2 - 5x + 6 = (x-2)(x-3)$`,
  },
  {
    id: "B-003",
    titre: "Équations — Résolution par factorisation",
    theme: "algebre",
    type: "Calcul",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: true,
    enonce: `Résous les équations suivantes :\n\n**a)** $x^2 - 4x = 0$\n**b)** $x^2 - 9 = 0$\n**c)** $(2x-1)(x+3) = 0$\n**d)** $x^2 - 5x + 6 = 0$ (utilise la factorisation de l'exercice B-002)`,
    aide: `Un produit est nul si et seulement si **l'un de ses facteurs est nul**.\n\n$A \\times B = 0 \\Leftrightarrow A = 0 $ ou $ B = 0$\n\nFactorise d'abord l'expression !`,
    solution: `**a)** $x(x-4) = 0 \\Rightarrow x = 0$ ou $x = 4$\n\n**b)** $(x-3)(x+3) = 0 \\Rightarrow x = 3$ ou $x = -3$\n\n**c)** $2x - 1 = 0$ ou $x + 3 = 0 \\Rightarrow x = \\frac{1}{2}$ ou $x = -3$\n\n**d)** $(x-2)(x-3) = 0 \\Rightarrow x = 2$ ou $x = 3$`,
  },
  {
    id: "B-004",
    titre: "Système d'équations (style brevet)",
    theme: "algebre",
    type: "Problème",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: true,
    enonce: `**Problème :** Dans un parc, il y a des vélos et des tricycles. En tout, on compte **17 véhicules** et **41 roues**.\n\n**a)** Pose un système de deux équations à deux inconnues.\n**b)** Résous ce système par substitution ou par addition.\n**c)** Combien y a-t-il de vélos et de tricycles ?`,
    aide: `Appelle $v$ le nombre de vélos (2 roues) et $t$ le nombre de tricycles (3 roues).\n\n$$\\begin{cases} v + t = 17 \\\\ 2v + 3t = 41 \\end{cases}$$`,
    solution: `$$\\begin{cases} v + t = 17 \\\\ 2v + 3t = 41 \\end{cases}$$\n\nDe la 1ère équation : $v = 17 - t$\nSubstitution dans la 2ème : $2(17-t) + 3t = 41$\n$34 - 2t + 3t = 41 \\Rightarrow t = 7$\nDonc $v = 17 - 7 = 10$\n\n✅ **10 vélos et 7 tricycles**\n\nVérif roues : $2 \\times 10 + 3 \\times 7 = 20 + 21 = 41$ ✓`,
  },
  {
    id: "B-005",
    titre: "Fonctions affines",
    theme: "fonctions",
    type: "Analyse",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `Soit la fonction $f$ définie par $f(x) = -2x + 5$.\n\n**a)** Calcule $f(0)$, $f(2)$, $f(-1)$ et $f(\\frac{1}{2})$.\n**b)** Quelle est la pente (coefficient directeur) ? Que signifie-t-elle ?\n**c)** Pour quelle valeur de $x$ a-t-on $f(x) = 0$ ? (zéro de la fonction)\n**d)** Dresse un tableau de valeurs pour $x \\in \\{-2; -1; 0; 1; 2; 3\\}$ et trace la droite sur papier.`,
    aide: `Une fonction **affine** : $f(x) = ax + b$\n- $a$ = pente (si $a > 0$ : croissante ; si $a < 0$ : décroissante)\n- $b$ = ordonnée à l'origine (valeur en $x = 0$)\n\nPour le zéro : résous $f(x) = 0$.`,
    solution: `**a)** $f(0) = 5$, $f(2) = 1$, $f(-1) = 7$, $f(\\frac{1}{2}) = 4$\n\n**b)** Pente $a = -2$ : pour chaque unité de $x$ en plus, $f(x)$ diminue de 2.\n\n**c)** $-2x + 5 = 0 \\Rightarrow x = \\frac{5}{2} = 2{,}5$\n\n**d)** Tableau :\n| $x$ | -2 | -1 | 0 | 1 | 2 | 3 |\n|-----|----|----|---|---|---|---|\n| $f(x)$ | 9 | 7 | 5 | 3 | 1 | -1 |`,
  },
  {
    id: "B-006",
    titre: "Théorème de Thalès",
    theme: "geometrie",
    type: "Géométrie",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: true,
    enonce: `Dans le triangle $ABC$, les points $D$ et $E$ sont placés sur $[AB]$ et $[AC]$ respectivement, tels que $DE \\parallel BC$.\n\nOn a : $AD = 4$ cm, $AB = 10$ cm et $BC = 7{,}5$ cm.\n\n**a)** Calcule $DE$.\n**b)** Calcule $AE$ sachant que $AC = 12{,}5$ cm.`,
    aide: `**Théorème de Thalès :** Si $DE \\parallel BC$, alors :\n$$\\frac{AD}{AB} = \\frac{AE}{AC} = \\frac{DE}{BC}$$\n\nCette propriété est au programme du **brevet** tous les ans !`,
    solution: `**a)** $\\frac{AD}{AB} = \\frac{DE}{BC}$\n$$\\frac{4}{10} = \\frac{DE}{7{,}5} \\Rightarrow DE = \\frac{4 \\times 7{,}5}{10} = \\mathbf{3}$ **cm**\n\n**b)** $\\frac{AD}{AB} = \\frac{AE}{AC}$\n$$\\frac{4}{10} = \\frac{AE}{12{,}5} \\Rightarrow AE = \\frac{4 \\times 12{,}5}{10} = \\mathbf{5}$ **cm**`,
  },
  {
    id: "B-007",
    titre: "Trigonométrie dans le triangle rectangle",
    theme: "geometrie",
    type: "Géométrie",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: true,
    enonce: `Dans un triangle rectangle $ABC$ (angle droit en $A$), on a $BC = 10$ cm et $\\widehat{ABC} = 35°$.\n\n**a)** Fais un schéma.\n**b)** Calcule $AB$ (arrondi au mm).\n**c)** Calcule $AC$ (arrondi au mm).\n**d)** Quelle est la valeur de $\\widehat{BCA}$ ?`,
    aide: `Dans un triangle rectangle, par rapport à l'angle $\\widehat{B}$ :\n- **côté adjacent** à $\\widehat{B}$ : $AB$ (entre B et l'angle droit)\n- **côté opposé** : $AC$\n- **hypoténuse** : $BC$\n\n$$\\cos(\\widehat{B}) = \\frac{\\text{adjacent}}{\\text{hypoténuse}} = \\frac{AB}{BC}$$\n$$\\sin(\\widehat{B}) = \\frac{\\text{opposé}}{\\text{hypoténuse}} = \\frac{AC}{BC}$$`,
    solution: `**b)** $\\cos(35°) = \\frac{AB}{10} \\Rightarrow AB = 10 \\cos(35°) \\approx 10 \\times 0{,}819 \\approx \\mathbf{8{,}2}$ **cm**\n\n**c)** $\\sin(35°) = \\frac{AC}{10} \\Rightarrow AC = 10 \\sin(35°) \\approx 10 \\times 0{,}574 \\approx \\mathbf{5{,}7}$ **cm**\n\n**d)** $\\widehat{BCA} = 90° - 35° = \\mathbf{55°}$`,
  },
  {
    id: "B-008",
    titre: "Statistiques — Indicateurs",
    theme: "stats",
    type: "Stats",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `Les notes de 10 élèves à un contrôle sont (sur 20) :\n$$7 \\quad 12 \\quad 15 \\quad 8 \\quad 11 \\quad 14 \\quad 9 \\quad 13 \\quad 10 \\quad 11$$\n\n**a)** Ordonne la série. Calcule la **moyenne**.\n**b)** Détermine la **médiane**, le **premier quartile** $Q_1$ et le **troisième quartile** $Q_3$.\n**c)** Calcule l'**étendue** et l'**écart interquartile** $Q_3 - Q_1$.`,
    aide: `Série ordonnée avec $n = 10$ valeurs :\n- **Médiane** = moyenne des 5e et 6e valeurs\n- **Q₁** = médiane des 5 premières valeurs\n- **Q₃** = médiane des 5 dernières valeurs`,
    solution: `Série ordonnée : $7, 8, 9, 10, 11, 11, 12, 13, 14, 15$\n\n**a)** Moyenne : $\\frac{7+8+9+10+11+11+12+13+14+15}{10} = \\frac{110}{10} = \\mathbf{11}$\n\n**b)** Médiane : $\\frac{11+11}{2} = \\mathbf{11}$\n$Q_1$ = médiane de $\\{7,8,9,10,11\\} = \\mathbf{9}$\n$Q_3$ = médiane de $\\{11,12,13,14,15\\} = \\mathbf{13}$\n\n**c)** Étendue = $15 - 7 = \\mathbf{8}$ ; EI = $Q_3 - Q_1 = 13 - 9 = \\mathbf{4}$`,
  },
  {
    id: "B-009",
    titre: "Probabilités",
    theme: "proba",
    type: "Probabilités",
    niveau: 2,
    xp: 15,
    papier: false,
    brevet: true,
    enonce: `On tire au hasard une carte dans un jeu de 52 cartes (4 couleurs : ♠ ♥ ♦ ♣, 13 valeurs chacune : As, 2 à 10, Valet, Dame, Roi).\n\nCalcule la probabilité d'obtenir :\n**a)** Un cœur ♥\n**b)** Un roi\n**c)** La dame de pique\n**d)** Un nombre pair (2, 4, 6, 8 ou 10)\n**e)** Un roi ou un cœur`,
    aide: `**Probabilité** = $\\frac{\\text{nombre de cas favorables}}{\\text{nombre de cas possibles}}$\n\nLe jeu comporte 52 cartes au total.\n\nPour **e)**, attention au roi de cœur qui est compté deux fois !`,
    solution: `**a)** 13 cœurs → $P = \\frac{13}{52} = \\frac{1}{4}$\n\n**b)** 4 rois → $P = \\frac{4}{52} = \\frac{1}{13}$\n\n**c)** 1 seule carte → $P = \\frac{1}{52}$\n\n**d)** 5 valeurs × 4 couleurs = 20 cartes → $P = \\frac{20}{52} = \\frac{5}{13}$\n\n**e)** Rois : 4, Cœurs : 13, Roi de cœur : 1\nUnion : $4 + 13 - 1 = 16$ → $P = \\frac{16}{52} = \\frac{4}{13}$`,
  },
  {
    id: "B-010",
    titre: "Racines carrées et calcul littéral",
    theme: "calcul",
    type: "Calcul",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: true,
    enonce: `**a)** Simplifie : $\\sqrt{48} + 2\\sqrt{3}$\n\n**b)** Calcule : $\\sqrt{5} \\times \\sqrt{20}$\n\n**c)** Simplifie : $(\\sqrt{7} - 1)(\\sqrt{7} + 1)$\n\n**d)** Mets sous la forme $a\\sqrt{2}$ : $\\sqrt{18} + \\sqrt{8} - \\sqrt{50}$`,
    aide: `On simplifie une racine en cherchant un **carré parfait** :\n$$\\sqrt{48} = \\sqrt{16 \\times 3} = \\sqrt{16} \\times \\sqrt{3} = 4\\sqrt{3}$$\n\nOn peut aussi utiliser $(a-b)(a+b) = a^2 - b^2$.`,
    solution: `**a)** $\\sqrt{48} + 2\\sqrt{3} = 4\\sqrt{3} + 2\\sqrt{3} = \\mathbf{6\\sqrt{3}}$\n\n**b)** $\\sqrt{5 \\times 20} = \\sqrt{100} = \\mathbf{10}$\n\n**c)** $(\\sqrt{7})^2 - 1^2 = 7 - 1 = \\mathbf{6}$\n\n**d)** $\\sqrt{18} = 3\\sqrt{2}$, $\\sqrt{8} = 2\\sqrt{2}$, $\\sqrt{50} = 5\\sqrt{2}$\n$\\Rightarrow 3\\sqrt{2} + 2\\sqrt{2} - 5\\sqrt{2} = \\mathbf{0}$`,
  },
  {
    id: "B-011",
    titre: "Notation scientifique",
    theme: "calcul",
    type: "Calcul",
    niveau: 2,
    xp: 10,
    papier: false,
    brevet: false,
    enonce: `**a)** Écris en notation scientifique : $0{,}000\\ 432$ et $5\\ 800\\ 000$\n\n**b)** Calcule et donne le résultat en notation scientifique :\n$$\\frac{6 \\times 10^8}{3 \\times 10^3} \\qquad \\text{et} \\qquad (2{,}4 \\times 10^{-3}) \\times (5 \\times 10^7)$$`,
    aide: `Notation scientifique : $a \\times 10^n$ où $1 \\leq a < 10$.\n\n$0{,}000432 = 4{,}32 \\times 10^{-4}$ (la virgule a bougé de 4 rangs vers la droite)`,
    solution: `**a)** $0{,}000\\ 432 = \\mathbf{4{,}32 \\times 10^{-4}}$\n$5\\ 800\\ 000 = \\mathbf{5{,}8 \\times 10^6}$\n\n**b)** $\\frac{6 \\times 10^8}{3 \\times 10^3} = 2 \\times 10^5 = \\mathbf{200\\ 000}$\n\n$(2{,}4 \\times 5) \\times 10^{-3+7} = 12 \\times 10^4 = \\mathbf{1{,}2 \\times 10^5}$`,
  },
  {
    id: "B-012",
    titre: "Problème de synthèse — Type brevet (APMEP 2024)",
    theme: "geometrie",
    type: "Problème",
    niveau: 4,
    xp: 30,
    papier: true,
    brevet: true,
    enonce: `Un mât vertical de hauteur $MH = 6$ m est fixé au sol en $H$. Un câble part du sommet $M$ et rejoint le sol en un point $P$ tel que $HP = 4$ m. La base du mât, le câble et le sol forment un triangle rectangle en $H$.\n\n**a)** Fais un schéma légendé.\n**b)** Calcule la longueur du câble $MP$ (valeur exacte, puis valeur approchée au cm près).\n**c)** Calcule l'angle $\\widehat{MPH}$ que fait le câble avec le sol (arrondi au degré).\n**d)** On souhaite peindre le triangle formé. Quelle est son aire en m² ?`,
    aide: `Le triangle $MHP$ est rectangle en $H$.\n\n**b)** Utilise le théorème de Pythagore.\n**c)** Dans le triangle rectangle, $\\tan(\\widehat{MPH}) = \\frac{MH}{HP}$ (côté opposé / côté adjacent par rapport à $\\widehat{MPH}$).\n\n**d)** Aire = $\\frac{\\text{base} \\times \\text{hauteur}}{2}$`,
    solution: `**b)** $MP^2 = MH^2 + HP^2 = 36 + 16 = 52$\n$MP = \\sqrt{52} = 2\\sqrt{13} \\approx \\mathbf{7{,}21}$ **m**\n\n**c)** $\\tan(\\widehat{MPH}) = \\frac{6}{4} = 1{,}5$\n$\\widehat{MPH} = \\arctan(1{,}5) \\approx \\mathbf{56°}$\n\n**d)** Aire $= \\frac{4 \\times 6}{2} = \\mathbf{12}$ **m²**`,
  },
];

/* ===== EXERCICES — PARCOURS C (Cap Seconde) ===== */

const EXERCICES_C = [
  {
    id: "C-001",
    titre: "Ensembles de nombres et intervalles",
    theme: "algebre",
    type: "Définitions",
    niveau: 1,
    xp: 10,
    papier: false,
    brevet: false,
    enonce: `**a)** Classe chaque nombre dans le(s) ensemble(s) auquel il appartient ($\\mathbb{N}$, $\\mathbb{Z}$, $\\mathbb{D}$, $\\mathbb{Q}$, $\\mathbb{R}$) :\n$$-5 \\qquad \\frac{3}{7} \\qquad \\sqrt{4} \\qquad \\sqrt{2} \\qquad 0{,}\\overline{3} \\qquad \\pi$$\n\n**b)** Écris en notation d'intervalle :\n- $-3 \\leq x < 5$\n- $x > 2$ ou $x \\leq -1$\n- $|x| \\leq 4$`,
    aide: `$\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q} \\subset \\mathbb{R}$\n\n$\\sqrt{2}$ et $\\pi$ sont **irrationnels** (ils sont dans $\\mathbb{R}$ mais pas dans $\\mathbb{Q}$).\n\n$0{,}\\overline{3} = \\frac{1}{3}$ est rationnel.\n\nNotation d'intervalle : $[$ = inclus, $]$ = inclus, $]$ ou $[$ = exclu.`,
    solution: `**a)** \n- $-5$ : $\\mathbb{Z}$, $\\mathbb{Q}$, $\\mathbb{R}$\n- $\\frac{3}{7}$ : $\\mathbb{Q}$, $\\mathbb{R}$\n- $\\sqrt{4} = 2$ : $\\mathbb{N}$, $\\mathbb{Z}$, $\\mathbb{Q}$, $\\mathbb{R}$\n- $\\sqrt{2}$ : $\\mathbb{R}$ uniquement (irrationnel)\n- $0{,}\\overline{3} = \\frac{1}{3}$ : $\\mathbb{Q}$, $\\mathbb{R}$\n- $\\pi$ : $\\mathbb{R}$ uniquement (irrationnel)\n\n**b)**\n- $-3 \\leq x < 5$ : $[-3\\,;\\,5[$\n- $x > 2$ ou $x \\leq -1$ : $]-\\infty\\,;\\,-1] \\cup ]2\\,;\\,+\\infty[$\n- $|x| \\leq 4 \\Leftrightarrow -4 \\leq x \\leq 4$ : $[-4\\,;\\,4]$`,
  },
  {
    id: "C-002",
    titre: "Valeur absolue et inéquations",
    theme: "algebre",
    type: "Calcul",
    niveau: 2,
    xp: 20,
    papier: true,
    brevet: false,
    enonce: `Résous les inéquations suivantes en donnant la solution sous forme d'intervalle :\n\n**a)** $|2x - 3| < 5$\n**b)** $|x + 1| \\geq 3$\n**c)** $2x - 1 \\leq 3x + 5$`,
    aide: `**Règle :** $|A| < k \\Leftrightarrow -k < A < k$ (avec $k > 0$)\n\n**Règle :** $|A| \\geq k \\Leftrightarrow A \\leq -k$ ou $A \\geq k$`,
    solution: `**a)** $|2x-3| < 5 \\Leftrightarrow -5 < 2x-3 < 5$\n$\\Leftrightarrow -2 < 2x < 8 \\Leftrightarrow -1 < x < 4$\nSolution : $\\mathbf{]-1\\,;\\,4[}$\n\n**b)** $|x+1| \\geq 3 \\Leftrightarrow x+1 \\leq -3$ ou $x+1 \\geq 3$\n$\\Leftrightarrow x \\leq -4$ ou $x \\geq 2$\nSolution : $\\mathbf{]-\\infty\\,;\\,-4] \\cup [2\\,;\\,+\\infty[}$\n\n**c)** $2x - 3x \\leq 5 + 1 \\Leftrightarrow -x \\leq 6 \\Leftrightarrow x \\geq -6$\nSolution : $\\mathbf{[-6\\,;\\,+\\infty[}$`,
  },
  {
    id: "C-003",
    titre: "Vecteurs — Opérations de base",
    theme: "geometrie",
    type: "Géométrie",
    niveau: 2,
    xp: 20,
    papier: true,
    brevet: false,
    enonce: `Dans un repère orthonormé, $A(1\\,;\\,2)$, $B(4\\,;\\,-1)$, $C(-2\\,;\\,5)$ et $D(7\\,;\\,3)$.\n\n**a)** Calcule les coordonnées de $\\overrightarrow{AB}$ et $\\overrightarrow{CD}$.\n**b)** Calcule $\\overrightarrow{AB} + \\overrightarrow{CD}$.\n**c)** Les vecteurs $\\overrightarrow{AB}$ et $\\overrightarrow{AC}$ sont-ils colinéaires ? (calcule le déterminant)\n**d)** Calcule les coordonnées du milieu $M$ de $[AB]$.`,
    aide: `$\\overrightarrow{AB} = \\begin{pmatrix} x_B - x_A \\\\ y_B - y_A \\end{pmatrix}$\n\nDeux vecteurs $\\overrightarrow{u}(a;b)$ et $\\overrightarrow{v}(c;d)$ sont **colinéaires** si $ad - bc = 0$.\n\nMilieu de $[AB]$ : $M = \\left(\\frac{x_A+x_B}{2}\\,;\\,\\frac{y_A+y_B}{2}\\right)$`,
    solution: `**a)** $\\overrightarrow{AB} = \\begin{pmatrix} 3 \\\\ -3 \\end{pmatrix}$, $\\overrightarrow{CD} = \\begin{pmatrix} 9 \\\\ -2 \\end{pmatrix}$\n\n**b)** $\\overrightarrow{AB} + \\overrightarrow{CD} = \\begin{pmatrix} 12 \\\\ -5 \\end{pmatrix}$\n\n**c)** $\\overrightarrow{AC} = \\begin{pmatrix} -3 \\\\ 3 \\end{pmatrix}$\nDéterminant : $3 \\times 3 - (-3)(-3) = 9 - 9 = 0$\n✅ **Colinéaires** (en fait $\\overrightarrow{AC} = -\\overrightarrow{AB}$, donc C est sur la droite (AB))\n\n**d)** $M = \\left(\\frac{5}{2}\\,;\\,\\frac{1}{2}\\right)$`,
  },
  {
    id: "C-004",
    titre: "Fonctions — Variations et extrema",
    theme: "fonctions",
    type: "Analyse",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: false,
    enonce: `Soit $f(x) = x^2 - 4x + 3$.\n\n**a)** Calcule $f(-1)$, $f(0)$, $f(1)$, $f(2)$, $f(3)$, $f(4)$, $f(5)$.\n**b)** Représente graphiquement $f$ sur $[-1\\,;\\,5]$ (sur papier).\n**c)** La fonction $f$ a-t-elle un minimum ? Si oui, pour quelle valeur de $x$ et quelle est la valeur minimale ?\n**d)** Sur quel(s) intervalle(s) la fonction est-elle décroissante ? Croissante ?`,
    aide: `À partir du tableau de valeurs, observe comment varie $f$ :\n- Si les valeurs diminuent : la fonction est **décroissante**\n- Si les valeurs augmentent : la fonction est **croissante**\n\nLe **minimum** est la plus petite valeur atteinte par la fonction.`,
    solution: `**a)** $f(-1)=8$, $f(0)=3$, $f(1)=0$, $f(2)=-1$, $f(3)=0$, $f(4)=3$, $f(5)=8$\n\n**c)** Minimum de $f$ : $\\mathbf{-1}$, atteint pour $x = \\mathbf{2}$\n\n**d)** $f$ est **décroissante** sur $]-\\infty\\,;\\,2]$ et **croissante** sur $[2\\,;\\,+\\infty[$`,
  },
  {
    id: "C-005",
    titre: "Fonctions de référence",
    theme: "fonctions",
    type: "Analyse",
    niveau: 2,
    xp: 15,
    papier: true,
    brevet: false,
    enonce: `On considère les fonctions $f(x) = x^2$, $g(x) = \\frac{1}{x}$ et $h(x) = \\sqrt{x}$.\n\n**a)** Quel est le domaine de définition de chacune ?\n**b)** Pour chaque fonction, dis si elle est croissante, décroissante ou ni l'un ni l'autre, et sur quel domaine.\n**c)** Soit $p(x) = (x-2)^2 + 1$. Comment obtient-on la courbe de $p$ à partir de celle de $f$ ? Quel est le minimum de $p$ ?`,
    aide: `$g(x) = \\frac{1}{x}$ n'est pas définie en $x = 0$ et $h(x) = \\sqrt{x}$ n'est définie que pour $x \\geq 0$.\n\n$p(x) = f(x-2) + 1$ : c'est $f$ **décalée** de 2 vers la droite et 1 vers le haut.`,
    solution: `**a)**\n- $f$ : $\\mathbb{R}$ ; $g$ : $\\mathbb{R} \\setminus \\{0\\}$ ; $h$ : $[0\\,;\\,+\\infty[$\n\n**b)**\n- $f$ : décroissante sur $]-\\infty\\,;\\,0]$, croissante sur $[0\\,;\\,+\\infty[$\n- $g$ : décroissante sur $]-\\infty\\,;\\,0[$ et sur $]0\\,;\\,+\\infty[$\n- $h$ : croissante sur $[0\\,;\\,+\\infty[$\n\n**c)** La courbe de $p$ s'obtient en **translatant** celle de $f$ de 2 vers la droite et 1 vers le haut.\nMinimum de $p$ : $\\mathbf{1}$, atteint pour $x = \\mathbf{2}$.`,
  },
  {
    id: "C-006",
    titre: "Droites dans le plan — Équations et positions relatives",
    theme: "geometrie",
    type: "Géométrie",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: false,
    enonce: `Soient $d_1 : y = 2x + 1$ et $d_2 : y = -\\frac{1}{2}x + 3$.\n\n**a)** Ces droites sont-elles parallèles, perpendiculaires ou sécantes (sans être perpendiculaires) ?\n**b)** Calcule les coordonnées du point d'intersection de $d_1$ et $d_2$.\n**c)** Quelle est l'équation de la droite $d_3$ passant par $A(0\\,;\\,4)$ et parallèle à $d_1$ ?`,
    aide: `Deux droites $y = a_1 x + b_1$ et $y = a_2 x + b_2$ sont :\n- **parallèles** si $a_1 = a_2$\n- **perpendiculaires** si $a_1 \\times a_2 = -1$\n\nPour l'intersection, résous le système.`,
    solution: `**a)** Pentes : $a_1 = 2$ et $a_2 = -\\frac{1}{2}$.\n$a_1 \\times a_2 = 2 \\times (-\\frac{1}{2}) = -1$\n✅ Les droites sont **perpendiculaires**.\n\n**b)** $2x + 1 = -\\frac{1}{2}x + 3 \\Rightarrow \\frac{5}{2}x = 2 \\Rightarrow x = \\frac{4}{5}$\n$y = 2 \\times \\frac{4}{5} + 1 = \\frac{13}{5}$\nIntersection : $\\mathbf{\\left(\\frac{4}{5}\\,;\\,\\frac{13}{5}\\right)}$\n\n**c)** $d_3$ parallèle à $d_1$ donc même pente $a = 2$, et passe par $A(0\\,;\\,4)$ donc $b = 4$.\n$d_3 : y = 2x + 4$`,
  },
  {
    id: "C-007",
    titre: "Statistiques — Diagramme en boîte",
    theme: "stats",
    type: "Stats",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: false,
    enonce: `Les temps (en minutes) de 12 élèves pour résoudre un problème sont :\n$$18 \\quad 25 \\quad 12 \\quad 30 \\quad 22 \\quad 15 \\quad 28 \\quad 35 \\quad 20 \\quad 24 \\quad 17 \\quad 40$$\n\n**a)** Ordonne la série. Détermine min, max, médiane, $Q_1$, $Q_3$.\n**b)** Calcule l'écart interquartile. Y a-t-il des valeurs aberrantes (seuils : $Q_1 - 1{,}5 \\times EI$ et $Q_3 + 1{,}5 \\times EI$) ?\n**c)** Trace un diagramme en boîte (boîte à moustaches) sur papier.`,
    aide: `Pour $n = 12$ valeurs ordonnées :\n- **Médiane** = $\\frac{6^e + 7^e \\text{ valeur}}{2}$\n- $Q_1$ = médiane des 6 premières\n- $Q_3$ = médiane des 6 dernières`,
    solution: `Série ordonnée : $12, 15, 17, 18, 20, 22, 24, 25, 28, 30, 35, 40$\n\n**a)** min = 12, max = 40\nMédiane = $\\frac{22+24}{2} = \\mathbf{23}$\n$Q_1 = \\frac{17+18}{2} = \\mathbf{17{,}5}$ ; $Q_3 = \\frac{28+30}{2} = \\mathbf{29}$\n\n**b)** EI = $29 - 17{,}5 = \\mathbf{11{,}5}$\nSeuil bas : $17{,}5 - 17{,}25 = 0{,}25$ ; Seuil haut : $29 + 17{,}25 = 46{,}25$\nToutes les valeurs sont entre 0{,}25 et 46{,}25 → **pas de valeur aberrante**`,
  },
  {
    id: "C-008",
    titre: "Probabilités — Dénombrement",
    theme: "proba",
    type: "Probabilités",
    niveau: 3,
    xp: 20,
    papier: true,
    brevet: false,
    enonce: `On lance simultanément deux dés cubiques équilibrés à 6 faces, numérotées de 1 à 6.\n\n**a)** Combien y a-t-il d'issues possibles ? (construis éventuellement un tableau)\n**b)** Calcule la probabilité que la somme des deux dés soit égale à 7.\n**c)** Calcule la probabilité que la somme soit strictement supérieure à 9.\n**d)** Calcule la probabilité que les deux dés donnent le même nombre.`,
    aide: `Il y a $6 \\times 6 = 36$ issues équiprobables.\n\nDresse un tableau des sommes (lignes = dé 1, colonnes = dé 2) pour compter facilement.`,
    solution: `**a)** 36 issues\n\n**b)** Somme = 7 : $(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$ → 6 issues\n$P = \\frac{6}{36} = \\mathbf{\\frac{1}{6}}$\n\n**c)** Somme > 9 : sommes 10, 11, 12\n$(4,6),(5,5),(6,4)$ → 3 ; $(5,6),(6,5)$ → 2 ; $(6,6)$ → 1 → total 6 issues\n$P = \\frac{6}{36} = \\mathbf{\\frac{1}{6}}$\n\n**d)** $(1,1),(2,2),(3,3),(4,4),(5,5),(6,6)$ → 6 issues\n$P = \\frac{6}{36} = \\mathbf{\\frac{1}{6}}$`,
  },
  {
    id: "C-009",
    titre: "Problème de synthèse — Fonctions et économie",
    theme: "fonctions",
    type: "Problème",
    niveau: 4,
    xp: 30,
    papier: true,
    brevet: false,
    enonce: `Un artisan produit des objets. Son bénéfice hebdomadaire (en euros) en fonction du nombre $n$ d'objets produits est :\n$$B(n) = -n^2 + 60n - 500 \\quad \\text{pour } n \\in [0\\,;\\,60]$$\n\n**a)** Calcule $B(0)$, $B(10)$, $B(30)$, $B(50)$, $B(60)$.\n**b)** Pour quelle valeur de $n$ le bénéfice est-il maximal ?\n**c)** Pour quelles valeurs de $n$ l'artisan fait-il une perte ($B(n) < 0$) ? (résous $-n^2 + 60n - 500 < 0$)`,
    aide: `**b)** La parabole $B(n) = -n^2 + 60n - 500$ a son sommet en $n = -\\frac{60}{2 \\times (-1)} = 30$.\n\n**c)** Résous d'abord $-n^2 + 60n - 500 = 0$, puis étudie le signe.`,
    solution: `**a)** $B(0) = -500$, $B(10) = -100+600-500 = 0$, $B(30) = 400$, $B(50) = 0$, $B(60) = -500$\n\n**b)** Maximum pour $n = \\mathbf{30}$ objets, bénéfice maximal $= \\mathbf{400}$ **€**\n\n**c)** $-n^2 + 60n - 500 = 0 \\Rightarrow n = 10$ ou $n = 50$ (racines)\nComme le coefficient de $n^2$ est négatif, $B(n) < 0$ pour $n < 10$ ou $n > 50$.\nL'artisan fait une perte si $n \\in [0\\,;\\,10[$ **ou** $n \\in ]50\\,;\\,60]$.`,
  },
  {
    id: "C-010",
    titre: "Probabilités conditionnelles — Introduction",
    theme: "proba",
    type: "Probabilités",
    niveau: 4,
    xp: 25,
    papier: true,
    brevet: false,
    enonce: `Dans une classe de 30 élèves :\n- 18 jouent au foot (F)\n- 12 jouent à la pétanque (P)\n- 6 jouent aux deux\n\n**a)** Combien jouent à au moins un des deux sports ?\n**b)** Un élève est choisi au hasard. Quelle est la probabilité qu'il joue au foot mais pas à la pétanque ?\n**c)** Parmi les élèves qui jouent au foot, quelle proportion joue aussi à la pétanque ?\n**d)** Les événements « jouer au foot » et « jouer à la pétanque » sont-ils incompatibles ? Indépendants ?`,
    aide: `Utilise un **diagramme de Venn** ou un tableau.\n\nFormule d'union : $|F \\cup P| = |F| + |P| - |F \\cap P|$\n\n**Indépendance :** $P(F \\cap P) = P(F) \\times P(P)$ ?`,
    solution: `**a)** $|F \\cup P| = 18 + 12 - 6 = \\mathbf{24}$ élèves (6 ne jouent ni à l'un ni à l'autre)\n\n**b)** Foot seulement : $18 - 6 = 12$ élèves\n$P = \\frac{12}{30} = \\mathbf{\\frac{2}{5}}$\n\n**c)** Parmi les 18 qui jouent au foot, 6 jouent aussi à la pétanque : $\\frac{6}{18} = \\mathbf{\\frac{1}{3}}$\n\n**d)** Pas incompatibles (6 jouent aux deux).\nIndépendants ? $P(F) \\times P(P) = \\frac{18}{30} \\times \\frac{12}{30} = \\frac{216}{900} = 0{,}24$\n$P(F \\cap P) = \\frac{6}{30} = 0{,}2 \\neq 0{,}24$ → **pas indépendants**.`,
  },
];

/* ===== AUTOMATISMES BAC (format épreuve anticipée 1ère) ===== */
/* 6 points, sans calculatrice, questions flash */

const AUTOMATISMES = [
  {
    id: "AUTO-001",
    question: "Calcule $\\sqrt{72}$ en forme simplifiée.",
    options: ["$6\\sqrt{2}$", "$8\\sqrt{3}$", "$6\\sqrt{3}$", "$36\\sqrt{2}$"],
    reponse: 0,
    explication: "$\\sqrt{72} = \\sqrt{36 \\times 2} = 6\\sqrt{2}$",
    xp: 5,
  },
  {
    id: "AUTO-002",
    question: "Si $f(x) = 3x - 5$, alors $f(-2)$ vaut :",
    options: ["$-11$", "$11$", "$-1$", "$1$"],
    reponse: 0,
    explication: "$f(-2) = 3 \\times (-2) - 5 = -6 - 5 = -11$",
    xp: 5,
  },
  {
    id: "AUTO-003",
    question: "L'intervalle $[-3\\,;\\,5[$ :",
    options: ["Contient $-3$ et $5$", "Contient $-3$ mais pas $5$", "Contient $5$ mais pas $-3$", "Ne contient ni $-3$ ni $5$"],
    reponse: 1,
    explication: "$[$ = crochet fermé ⟹ $-3$ inclus. $[$ ouvert à droite ⟹ $5$ exclu.",
    xp: 5,
  },
  {
    id: "AUTO-004",
    question: "La droite $y = -2x + 3$ est :",
    options: ["Croissante", "Décroissante", "Constante", "Non définie"],
    reponse: 1,
    explication: "Le coefficient directeur $a = -2 < 0$, donc la droite est décroissante.",
    xp: 5,
  },
  {
    id: "AUTO-005",
    question: "$2^3 \\times 2^{-1} = $",
    options: ["$2^2 = 4$", "$2^4 = 16$", "$2^{-3}$", "$4^2 = 16$"],
    reponse: 0,
    explication: "$2^3 \\times 2^{-1} = 2^{3+(-1)} = 2^2 = 4$",
    xp: 5,
  },
  {
    id: "AUTO-006",
    question: "Les vecteurs $\\overrightarrow{u}\\begin{pmatrix}2\\\\4\\end{pmatrix}$ et $\\overrightarrow{v}\\begin{pmatrix}1\\\\2\\end{pmatrix}$ sont :",
    options: ["Perpendiculaires", "Colinéaires", "Ni l'un ni l'autre", "Opposés"],
    reponse: 1,
    explication: "Déterminant : $2 \\times 2 - 4 \\times 1 = 0$ ⟹ colinéaires. D'ailleurs $\\overrightarrow{u} = 2\\overrightarrow{v}$.",
    xp: 5,
  },
  {
    id: "AUTO-007",
    question: "$A$ et $B$ sont indépendants, $P(A) = 0{,}4$, $P(B) = 0{,}3$. Alors $P(A \\cap B) = $",
    options: ["$0{,}7$", "$0{,}1$", "$0{,}12$", "$0{,}013$"],
    reponse: 2,
    explication: "Par indépendance : $P(A \\cap B) = P(A) \\times P(B) = 0{,}4 \\times 0{,}3 = 0{,}12$",
    xp: 5,
  },
  {
    id: "AUTO-008",
    question: "L'image de $x = -3$ par $f(x) = x^2 - 2$ est :",
    options: ["$7$", "$11$", "$-7$", "$-11$"],
    reponse: 0,
    explication: "$f(-3) = (-3)^2 - 2 = 9 - 2 = 7$",
    xp: 5,
  },
  {
    id: "AUTO-009",
    question: "$\\dfrac{3}{4} - \\dfrac{1}{6} = $",
    options: ["$\\dfrac{2}{10} = \\dfrac{1}{5}$", "$\\dfrac{7}{12}$", "$\\dfrac{1}{2}$", "$\\dfrac{11}{12}$"],
    reponse: 1,
    explication: "$\\frac{3}{4} - \\frac{1}{6} = \\frac{9}{12} - \\frac{2}{12} = \\frac{7}{12}$",
    xp: 5,
  },
  {
    id: "AUTO-010",
    question: "Dans un triangle rectangle, si les deux côtés de l'angle droit mesurent 5 et 12, l'hypoténuse mesure :",
    options: ["$8$", "$13$", "$\\sqrt{17}$", "$17$"],
    reponse: 1,
    explication: "$h^2 = 5^2 + 12^2 = 25 + 144 = 169 = 13^2$, donc $h = 13$ (triplet pythagoricien 5-12-13).",
    xp: 5,
  },
  {
    id: "AUTO-011",
    question: "Factoriser $x^2 - 16$ :",
    options: ["$(x-4)^2$", "$(x+4)^2$", "$(x-4)(x+4)$", "$x(x-16)$"],
    reponse: 2,
    explication: "$x^2 - 16 = x^2 - 4^2 = (x-4)(x+4)$ (identité remarquable $a^2 - b^2$)",
    xp: 5,
  },
  {
    id: "AUTO-012",
    question: "La médiane d'une série de 8 valeurs ordonnées est :",
    options: ["La 4e valeur", "La 5e valeur", "La moyenne des 4e et 5e valeurs", "La valeur centrale"],
    reponse: 2,
    explication: "Pour $n$ pair, la médiane est la moyenne des valeurs de rang $\\frac{n}{2}$ et $\\frac{n}{2}+1$. Ici : rang 4 et rang 5.",
    xp: 5,
  },
  {
    id: "AUTO-013",
    question: "Le coefficient directeur de la droite passant par $(0\\,;\\,2)$ et $(4\\,;\\,6)$ est :",
    options: ["$2$", "$4$", "$1$", "$\\frac{1}{2}$"],
    reponse: 2,
    explication: "$a = \\frac{y_B - y_A}{x_B - x_A} = \\frac{6-2}{4-0} = \\frac{4}{4} = 1$",
    xp: 5,
  },
  {
    id: "AUTO-014",
    question: "Si $x \\in [-2\\,;\\,3[$, alors $2x \\in $",
    options: ["$[-4\\,;\\,6[$", "$[-4\\,;\\,6]$", "$]-4\\,;\\,6[$", "$]-4\\,;\\,6]$"],
    reponse: 0,
    explication: "$x = -2$ inclus ⟹ $2x = -4$ inclus. $x = 3$ exclu ⟹ $2x = 6$ exclu. Donc $[-4\\,;\\,6[$.",
    xp: 5,
  },
  {
    id: "AUTO-015",
    question: "$\\cos(60°) = $",
    options: ["$\\dfrac{\\sqrt{3}}{2}$", "$\\dfrac{1}{2}$", "$\\dfrac{\\sqrt{2}}{2}$", "$1$"],
    reponse: 1,
    explication: "Valeurs à connaître : $\\cos(30°) = \\frac{\\sqrt{3}}{2}$, $\\cos(45°) = \\frac{\\sqrt{2}}{2}$, $\\cos(60°) = \\frac{1}{2}$.",
    xp: 5,
  },
  {
    id: "AUTO-016",
    question: "Si $f$ est croissante sur $[a\\,;\\,b]$ et si $a < c < d < b$, alors :",
    options: ["$f(c) < f(d)$", "$f(c) > f(d)$", "$f(c) = f(d)$", "Impossible à dire"],
    reponse: 0,
    explication: "Par définition d'une fonction croissante : $c < d \\Rightarrow f(c) < f(d)$.",
    xp: 5,
  },
  {
    id: "AUTO-017",
    question: "$(3 + \\sqrt{5})(3 - \\sqrt{5}) = $",
    options: ["$9 - 5 = 4$", "$9 + 5 = 14$", "$3 - 5 = -2$", "$6$"],
    reponse: 0,
    explication: "$(a+b)(a-b) = a^2 - b^2 = 9 - (\\sqrt{5})^2 = 9 - 5 = 4$",
    xp: 5,
  },
  {
    id: "AUTO-018",
    question: "Résous $|x - 3| = 5$ :",
    options: ["$x = 8$ seulement", "$x = -2$ seulement", "$x = 8$ ou $x = -2$", "$x = 2$ ou $x = -8$"],
    reponse: 2,
    explication: "$|x-3| = 5 \\Leftrightarrow x-3 = 5$ ou $x-3 = -5 \\Leftrightarrow x = 8$ ou $x = -2$",
    xp: 5,
  },
  {
    id: "AUTO-019",
    question: "On lance un dé. Quelle est la probabilité d'obtenir un nombre premier ?",
    options: ["$\\dfrac{1}{2}$", "$\\dfrac{1}{3}$", "$\\dfrac{2}{3}$", "$\\dfrac{1}{6}$"],
    reponse: 0,
    explication: "Nombres premiers sur un dé : 2, 3, 5 → 3 cas sur 6. $P = \\frac{3}{6} = \\frac{1}{2}$.",
    xp: 5,
  },
  {
    id: "AUTO-020",
    question: "L'ensemble $\\mathbb{Q}$ est :",
    options: ["L'ensemble des entiers naturels", "L'ensemble des nombres décimaux", "L'ensemble des fractions $\\frac{p}{q}$, $q \\neq 0$", "L'ensemble des réels"],
    reponse: 2,
    explication: "$\\mathbb{Q}$ est l'ensemble des **rationnels** : tous les nombres qui peuvent s'écrire $\\frac{p}{q}$ avec $p, q$ entiers et $q \\neq 0$.",
    xp: 5,
  },
];

/* ===== DIAGNOSTIC (15 questions de placement) ===== */

const DIAGNOSTIC = [
  {
    id: "D-01",
    niveau: "primaire",
    question: "Calcule : $\\dfrac{3}{4} + \\dfrac{1}{6}$",
    options: ["$\\dfrac{4}{10} = \\dfrac{2}{5}$", "$\\dfrac{11}{12}$", "$\\dfrac{4}{12} = \\dfrac{1}{3}$", "$\\dfrac{9}{12}$"],
    reponse: 1,
    poids: { A: 3, B: 0, C: 0 },
  },
  {
    id: "D-02",
    niveau: "6eme",
    question: "Une réduction de 20 % est appliquée à un article à 50 €. Quel est le nouveau prix ?",
    options: ["$40$ €", "$45$ €", "$30$ €", "$10$ €"],
    reponse: 0,
    poids: { A: 2, B: 1, C: 0 },
  },
  {
    id: "D-03",
    niveau: "4eme",
    question: "Résous : $3x + 5 = 14$",
    options: ["$x = 3$", "$x = 4$", "$x = 6$", "$x = 2$"],
    reponse: 0,
    poids: { A: 3, B: 1, C: 0 },
  },
  {
    id: "D-04",
    niveau: "4eme",
    question: "Dans un triangle rectangle de côtés 3 et 4, l'hypoténuse vaut :",
    options: ["$5$", "$7$", "$\\sqrt{7}$", "$\\sqrt{5}$"],
    reponse: 0,
    poids: { A: 2, B: 2, C: 0 },
  },
  {
    id: "D-05",
    niveau: "3eme",
    question: "Développe $(x+3)^2$ :",
    options: ["$x^2 + 9$", "$x^2 + 6x + 9$", "$x^2 + 3x + 9$", "$x^2 + 6x$"],
    reponse: 1,
    poids: { A: 0, B: 3, C: 1 },
  },
  {
    id: "D-06",
    niveau: "3eme",
    question: "Factorise : $x^2 - 25$",
    options: ["$(x-5)^2$", "$(x+5)(x-5)$", "$(x-5)(x+25)$", "$x(x-25)$"],
    reponse: 1,
    poids: { A: 0, B: 3, C: 1 },
  },
  {
    id: "D-07",
    niveau: "3eme",
    question: "La pente de la droite $y = -3x + 7$ est :",
    options: ["$7$", "$-7$", "$3$", "$-3$"],
    reponse: 3,
    poids: { A: 0, B: 2, C: 2 },
  },
  {
    id: "D-08",
    niveau: "3eme",
    question: "Dans un triangle $ABC$ avec $D$ sur $AB$, $E$ sur $AC$, $DE \\parallel BC$, $AD=3$, $AB=9$, $BC=6$. Alors $DE$ vaut :",
    options: ["$2$", "$3$", "$4$", "$18$"],
    reponse: 0,
    poids: { A: 0, B: 3, C: 1 },
  },
  {
    id: "D-09",
    niveau: "3eme",
    question: "Simplifie $\\sqrt{50}$ :",
    options: ["$5\\sqrt{2}$", "$25\\sqrt{2}$", "$10\\sqrt{5}$", "$5\\sqrt{10}$"],
    reponse: 0,
    poids: { A: 0, B: 2, C: 1 },
  },
  {
    id: "D-10",
    niveau: "3eme",
    question: "Une série a pour médiane 15, $Q_1 = 10$, $Q_3 = 20$. L'écart interquartile est :",
    options: ["$5$", "$10$", "$15$", "$25$"],
    reponse: 1,
    poids: { A: 0, B: 2, C: 2 },
  },
  {
    id: "D-11",
    niveau: "2nde",
    question: "L'intervalle $]-2\\,;\\,5]$ :",
    options: ["Contient $-2$ et $5$", "Contient $-2$ mais pas $5$", "Contient $5$ mais pas $-2$", "Ne contient aucune borne"],
    reponse: 2,
    poids: { A: 0, B: 0, C: 3 },
  },
  {
    id: "D-12",
    niveau: "2nde",
    question: "$\\overrightarrow{AB} = \\begin{pmatrix}3\\\\-2\\end{pmatrix}$. Les coordonnées de $B$ sachant que $A(1\\,;\\,4)$ sont :",
    options: ["$(4\\,;\\,2)$", "$(-2\\,;\\,6)$", "$(3\\,;\\,-2)$", "$(2\\,;\\,-1)$"],
    reponse: 0,
    poids: { A: 0, B: 0, C: 3 },
  },
  {
    id: "D-13",
    niveau: "2nde",
    question: "Soit $f(x) = x^2 - 4$. Pour quelle valeur de $x$ $f$ est-elle minimale ?",
    options: ["$x = -4$", "$x = 0$", "$x = 4$", "$x = 2$"],
    reponse: 1,
    poids: { A: 0, B: 1, C: 3 },
  },
  {
    id: "D-14",
    niveau: "2nde",
    question: "Résous $|x - 2| < 3$ :",
    options: ["$x \\in ]-1\\,;\\,5[$", "$x \\in [-1\\,;\\,5]$", "$x \\in ]-\\infty\\,;\\,-1[ \\cup ]5\\,;\\,+\\infty[$", "$x \\in ]-5\\,;\\,1[$"],
    reponse: 0,
    poids: { A: 0, B: 0, C: 3 },
  },
  {
    id: "D-15",
    niveau: "2nde",
    question: "Deux droites perpendiculaires ont des pentes $a_1$ et $a_2$. On a :",
    options: ["$a_1 = a_2$", "$a_1 + a_2 = 0$", "$a_1 \\times a_2 = -1$", "$a_1 \\times a_2 = 1$"],
    reponse: 2,
    poids: { A: 0, B: 0, C: 3 },
  },
];

/* Export (compatible avec un module bundler ou usage direct) */
if (typeof module !== 'undefined') {
  module.exports = { QUOTES, BADGES, BRAVO_MESSAGES, COURAGE_MESSAGES, EXERCICES_A, EXERCICES_B, EXERCICES_C, AUTOMATISMES, DIAGNOSTIC };
}
